<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Vehicle;

class VehicleSeeder extends Seeder
{
    public function run()
    {
        $vehicles = [
            [
                'number'                  => 42,
                'name'                    => 'Bus 42',
                'brand'                   => 'Mercedes',
                'model'                   => 'Citaro',
                'year'                    => 2019,
                'plate'                   => 'BG-123-AB',
                'seat_count'              => 42,
                'type'                    => 'bus',
                'status'                  => 'in_service',
                'fuel_type'               => 'diesel',
                'registration_expires_at' => '2027-03-15',
            ],
            [
                'number'                  => 17,
                'name'                    => 'Bus 17',
                'brand'                   => 'Volvo',
                'model'                   => '7900',
                'year'                    => 2021,
                'plate'                   => 'BG-456-CD',
                'seat_count'              => 38,
                'type'                    => 'bus',
                'status'                  => 'in_service',
                'fuel_type'               => 'hybrid',
                'registration_expires_at' => '2027-08-20',
            ],
            [
                'number'                  => 33,
                'name'                    => 'Bus 33',
                'brand'                   => 'Mercedes',
                'model'                   => 'Citaro',
                'year'                    => 2018,
                'plate'                   => 'BG-789-EF',
                'seat_count'              => 42,
                'type'                    => 'bus',
                'status'                  => 'in_service',
                'fuel_type'               => 'diesel',
                'registration_expires_at' => '2026-11-10',
            ],
            [
                'number'                  => 8,
                'name'                    => 'Tram 08',
                'brand'                   => 'CAF',
                'model'                   => 'Urbos',
                'year'                    => 2020,
                'plate'                   => 'BG-012-GH',
                'seat_count'              => 120,
                'type'                    => 'tram',
                'status'                  => 'in_service',
                'fuel_type'               => 'electric',
                'registration_expires_at' => '2028-05-01',
            ],
            [
                'number'                  => 55,
                'name'                    => 'Bus 55',
                'brand'                   => 'MAN',
                'model'                   => 'Lion\'s City',
                'year'                    => 2022,
                'plate'                   => 'BG-345-IJ',
                'seat_count'              => 40,
                'type'                    => 'bus',
                'status'                  => 'in_service',
                'fuel_type'               => 'diesel',
                'registration_expires_at' => '2028-01-25',
            ],
            [
                'number'                  => 12,
                'name'                    => 'Bus 12',
                'brand'                   => 'Mercedes',
                'model'                   => 'Citaro',
                'year'                    => 2017,
                'plate'                   => 'BG-678-KL',
                'seat_count'              => 42,
                'type'                    => 'bus',
                'status'                  => 'garage',
                'fuel_type'               => 'diesel',
                'registration_expires_at' => '2026-09-30',
            ],
            [
                'number'                  => 61,
                'name'                    => 'Bus 61',
                'brand'                   => 'Volvo',
                'model'                   => '8900',
                'year'                    => 2020,
                'plate'                   => 'BG-901-MN',
                'seat_count'              => 44,
                'type'                    => 'bus',
                'status'                  => 'in_service',
                'fuel_type'               => 'diesel',
                'registration_expires_at' => '2027-06-12',
            ],
            [
                'number'                  => 74,
                'name'                    => 'Bus 74',
                'brand'                   => 'MAN',
                'model'                   => 'Lion\'s City',
                'year'                    => 2023,
                'plate'                   => 'BG-234-OP',
                'seat_count'              => 40,
                'type'                    => 'bus',
                'status'                  => 'in_service',
                'fuel_type'               => 'diesel',
                'registration_expires_at' => '2029-02-18',
            ],
            [
                'number'                  => 88,
                'name'                    => 'Bus 88',
                'brand'                   => 'Mercedes',
                'model'                   => 'CapaCity',
                'year'                    => 2021,
                'plate'                   => 'BG-567-QR',
                'seat_count'              => 60,
                'type'                    => 'bus',
                'status'                  => 'in_service',
                'fuel_type'               => 'diesel',
                'registration_expires_at' => '2027-11-30',
            ],
            [
                'number'                  => 95,
                'name'                    => 'Bus 95',
                'brand'                   => 'Solaris',
                'model'                   => 'Urbino 12',
                'year'                    => 2022,
                'plate'                   => 'BG-890-ST',
                'seat_count'              => 38,
                'type'                    => 'bus',
                'status'                  => 'in_service',
                'fuel_type'               => 'electric',
                'registration_expires_at' => '2028-07-14',
            ],
            [
                'number'                  => 3,
                'name'                    => 'Tram 03',
                'brand'                   => 'Siemens',
                'model'                   => 'Combino',
                'year'                    => 2016,
                'plate'                   => 'BG-111-UV',
                'seat_count'              => 150,
                'type'                    => 'tram',
                'status'                  => 'in_service',
                'fuel_type'               => 'electric',
                'registration_expires_at' => '2026-12-01',
            ],
            [
                'number'                  => 11,
                'name'                    => 'Tram 11',
                'brand'                   => 'CAF',
                'model'                   => 'Urbos 3',
                'year'                    => 2023,
                'plate'                   => 'BG-222-WX',
                'seat_count'              => 130,
                'type'                    => 'tram',
                'status'                  => 'in_service',
                'fuel_type'               => 'electric',
                'registration_expires_at' => '2029-04-20',
            ],
            [
                'number'                  => 29,
                'name'                    => 'Bus 29',
                'brand'                   => 'Irisbus',
                'model'                   => 'Citelis',
                'year'                    => 2015,
                'plate'                   => 'BG-333-YZ',
                'seat_count'              => 36,
                'type'                    => 'bus',
                'status'                  => 'reserve',
                'fuel_type'               => 'diesel',
                'registration_expires_at' => '2026-08-05',
            ],
            [
                'number'                  => 47,
                'name'                    => 'Bus 47',
                'brand'                   => 'Volvo',
                'model'                   => '7900 Electric',
                'year'                    => 2023,
                'plate'                   => 'BG-444-AA',
                'seat_count'              => 40,
                'type'                    => 'bus',
                'status'                  => 'in_service',
                'fuel_type'               => 'electric',
                'registration_expires_at' => '2029-09-15',
            ],
            [
                'number'                  => 66,
                'name'                    => 'Bus 66',
                'brand'                   => 'MAN',
                'model'                   => 'Lion\'s City Hybrid',
                'year'                    => 2020,
                'plate'                   => 'BG-555-BB',
                'seat_count'              => 42,
                'type'                    => 'bus',
                'status'                  => 'in_service',
                'fuel_type'               => 'hybrid',
                'registration_expires_at' => '2027-03-28',
            ],
        ];

        foreach ($vehicles as $vehicle) {
            Vehicle::firstOrCreate(
                ['plate' => $vehicle['plate']],
                $vehicle
            );
        }
    }
}